

# This file was autogenerated by some hot garbage in the `uniffi` crate.
# Trust me, you don't want to mess with it!

# Common helper code.
#
# Ideally this would live in a separate .py file where it can be unittested etc
# in isolation, and perhaps even published as a re-useable package.
#
# However, it's important that the details of how this helper code works (e.g. the
# way that different builtin types are passed across the FFI) exactly match what's
# expected by the rust code on the other side of the interface. In practice right
# now that means coming from the exact some version of `uniffi` that was used to
# compile the rust component. The easiest way to ensure this is to bundle the Python
# helpers directly inline like we're doing here.

from __future__ import annotations
import os
import sys
import ctypes
import enum
import struct
import contextlib
import datetime
import threading
import itertools
import traceback
import typing
import platform

# Used for default argument values
_DEFAULT = object() # type: typing.Any


class _UniffiRustBuffer(ctypes.Structure):
    _fields_ = [
        ("capacity", ctypes.c_uint64),
        ("len", ctypes.c_uint64),
        ("data", ctypes.POINTER(ctypes.c_char)),
    ]

    @staticmethod
    def default():
        return _UniffiRustBuffer(0, 0, None)

    @staticmethod
    def alloc(size):
        return _uniffi_rust_call(_UniffiLib.ffi_pubkycore_rustbuffer_alloc, size)

    @staticmethod
    def reserve(rbuf, additional):
        return _uniffi_rust_call(_UniffiLib.ffi_pubkycore_rustbuffer_reserve, rbuf, additional)

    def free(self):
        return _uniffi_rust_call(_UniffiLib.ffi_pubkycore_rustbuffer_free, self)

    def __str__(self):
        return "_UniffiRustBuffer(capacity={}, len={}, data={})".format(
            self.capacity,
            self.len,
            self.data[0:self.len]
        )

    @contextlib.contextmanager
    def alloc_with_builder(*args):
        """Context-manger to allocate a buffer using a _UniffiRustBufferBuilder.

        The allocated buffer will be automatically freed if an error occurs, ensuring that
        we don't accidentally leak it.
        """
        builder = _UniffiRustBufferBuilder()
        try:
            yield builder
        except:
            builder.discard()
            raise

    @contextlib.contextmanager
    def consume_with_stream(self):
        """Context-manager to consume a buffer using a _UniffiRustBufferStream.

        The _UniffiRustBuffer will be freed once the context-manager exits, ensuring that we don't
        leak it even if an error occurs.
        """
        try:
            s = _UniffiRustBufferStream.from_rust_buffer(self)
            yield s
            if s.remaining() != 0:
                raise RuntimeError("junk data left in buffer at end of consume_with_stream")
        finally:
            self.free()

    @contextlib.contextmanager
    def read_with_stream(self):
        """Context-manager to read a buffer using a _UniffiRustBufferStream.

        This is like consume_with_stream, but doesn't free the buffer afterwards.
        It should only be used with borrowed `_UniffiRustBuffer` data.
        """
        s = _UniffiRustBufferStream.from_rust_buffer(self)
        yield s
        if s.remaining() != 0:
            raise RuntimeError("junk data left in buffer at end of read_with_stream")

class _UniffiForeignBytes(ctypes.Structure):
    _fields_ = [
        ("len", ctypes.c_int32),
        ("data", ctypes.POINTER(ctypes.c_char)),
    ]

    def __str__(self):
        return "_UniffiForeignBytes(len={}, data={})".format(self.len, self.data[0:self.len])


class _UniffiRustBufferStream:
    """
    Helper for structured reading of bytes from a _UniffiRustBuffer
    """

    def __init__(self, data, len):
        self.data = data
        self.len = len
        self.offset = 0

    @classmethod
    def from_rust_buffer(cls, buf):
        return cls(buf.data, buf.len)

    def remaining(self):
        return self.len - self.offset

    def _unpack_from(self, size, format):
        if self.offset + size > self.len:
            raise InternalError("read past end of rust buffer")
        value = struct.unpack(format, self.data[self.offset:self.offset+size])[0]
        self.offset += size
        return value

    def read(self, size):
        if self.offset + size > self.len:
            raise InternalError("read past end of rust buffer")
        data = self.data[self.offset:self.offset+size]
        self.offset += size
        return data

    def read_i8(self):
        return self._unpack_from(1, ">b")

    def read_u8(self):
        return self._unpack_from(1, ">B")

    def read_i16(self):
        return self._unpack_from(2, ">h")

    def read_u16(self):
        return self._unpack_from(2, ">H")

    def read_i32(self):
        return self._unpack_from(4, ">i")

    def read_u32(self):
        return self._unpack_from(4, ">I")

    def read_i64(self):
        return self._unpack_from(8, ">q")

    def read_u64(self):
        return self._unpack_from(8, ">Q")

    def read_float(self):
        v = self._unpack_from(4, ">f")
        return v

    def read_double(self):
        return self._unpack_from(8, ">d")

class _UniffiRustBufferBuilder:
    """
    Helper for structured writing of bytes into a _UniffiRustBuffer.
    """

    def __init__(self):
        self.rbuf = _UniffiRustBuffer.alloc(16)
        self.rbuf.len = 0

    def finalize(self):
        rbuf = self.rbuf
        self.rbuf = None
        return rbuf

    def discard(self):
        if self.rbuf is not None:
            rbuf = self.finalize()
            rbuf.free()

    @contextlib.contextmanager
    def _reserve(self, num_bytes):
        if self.rbuf.len + num_bytes > self.rbuf.capacity:
            self.rbuf = _UniffiRustBuffer.reserve(self.rbuf, num_bytes)
        yield None
        self.rbuf.len += num_bytes

    def _pack_into(self, size, format, value):
        with self._reserve(size):
            # XXX TODO: I feel like I should be able to use `struct.pack_into` here but can't figure it out.
            for i, byte in enumerate(struct.pack(format, value)):
                self.rbuf.data[self.rbuf.len + i] = byte

    def write(self, value):
        with self._reserve(len(value)):
            for i, byte in enumerate(value):
                self.rbuf.data[self.rbuf.len + i] = byte

    def write_i8(self, v):
        self._pack_into(1, ">b", v)

    def write_u8(self, v):
        self._pack_into(1, ">B", v)

    def write_i16(self, v):
        self._pack_into(2, ">h", v)

    def write_u16(self, v):
        self._pack_into(2, ">H", v)

    def write_i32(self, v):
        self._pack_into(4, ">i", v)

    def write_u32(self, v):
        self._pack_into(4, ">I", v)

    def write_i64(self, v):
        self._pack_into(8, ">q", v)

    def write_u64(self, v):
        self._pack_into(8, ">Q", v)

    def write_float(self, v):
        self._pack_into(4, ">f", v)

    def write_double(self, v):
        self._pack_into(8, ">d", v)

    def write_c_size_t(self, v):
        self._pack_into(ctypes.sizeof(ctypes.c_size_t) , "@N", v)
# A handful of classes and functions to support the generated data structures.
# This would be a good candidate for isolating in its own ffi-support lib.

class InternalError(Exception):
    pass

class _UniffiRustCallStatus(ctypes.Structure):
    """
    Error runtime.
    """
    _fields_ = [
        ("code", ctypes.c_int8),
        ("error_buf", _UniffiRustBuffer),
    ]

    # These match the values from the uniffi::rustcalls module
    CALL_SUCCESS = 0
    CALL_ERROR = 1
    CALL_UNEXPECTED_ERROR = 2

    @staticmethod
    def default():
        return _UniffiRustCallStatus(code=_UniffiRustCallStatus.CALL_SUCCESS, error_buf=_UniffiRustBuffer.default())

    def __str__(self):
        if self.code == _UniffiRustCallStatus.CALL_SUCCESS:
            return "_UniffiRustCallStatus(CALL_SUCCESS)"
        elif self.code == _UniffiRustCallStatus.CALL_ERROR:
            return "_UniffiRustCallStatus(CALL_ERROR)"
        elif self.code == _UniffiRustCallStatus.CALL_UNEXPECTED_ERROR:
            return "_UniffiRustCallStatus(CALL_UNEXPECTED_ERROR)"
        else:
            return "_UniffiRustCallStatus(<invalid code>)"

def _uniffi_rust_call(fn, *args):
    # Call a rust function
    return _uniffi_rust_call_with_error(None, fn, *args)

def _uniffi_rust_call_with_error(error_ffi_converter, fn, *args):
    # Call a rust function and handle any errors
    #
    # This function is used for rust calls that return Result<> and therefore can set the CALL_ERROR status code.
    # error_ffi_converter must be set to the _UniffiConverter for the error class that corresponds to the result.
    call_status = _UniffiRustCallStatus.default()

    args_with_error = args + (ctypes.byref(call_status),)
    result = fn(*args_with_error)
    _uniffi_check_call_status(error_ffi_converter, call_status)
    return result

def _uniffi_check_call_status(error_ffi_converter, call_status):
    if call_status.code == _UniffiRustCallStatus.CALL_SUCCESS:
        pass
    elif call_status.code == _UniffiRustCallStatus.CALL_ERROR:
        if error_ffi_converter is None:
            call_status.error_buf.free()
            raise InternalError("_uniffi_rust_call_with_error: CALL_ERROR, but error_ffi_converter is None")
        else:
            raise error_ffi_converter.lift(call_status.error_buf)
    elif call_status.code == _UniffiRustCallStatus.CALL_UNEXPECTED_ERROR:
        # When the rust code sees a panic, it tries to construct a _UniffiRustBuffer
        # with the message.  But if that code panics, then it just sends back
        # an empty buffer.
        if call_status.error_buf.len > 0:
            msg = _UniffiConverterString.lift(call_status.error_buf)
        else:
            msg = "Unknown rust panic"
        raise InternalError(msg)
    else:
        raise InternalError("Invalid _UniffiRustCallStatus code: {}".format(
            call_status.code))

def _uniffi_trait_interface_call(call_status, make_call, write_return_value):
    try:
        return write_return_value(make_call())
    except Exception as e:
        call_status.code = _UniffiRustCallStatus.CALL_UNEXPECTED_ERROR
        call_status.error_buf = _UniffiConverterString.lower(repr(e))

def _uniffi_trait_interface_call_with_error(call_status, make_call, write_return_value, error_type, lower_error):
    try:
        try:
            return write_return_value(make_call())
        except error_type as e:
            call_status.code = _UniffiRustCallStatus.CALL_ERROR
            call_status.error_buf = lower_error(e)
    except Exception as e:
        call_status.code = _UniffiRustCallStatus.CALL_UNEXPECTED_ERROR
        call_status.error_buf = _UniffiConverterString.lower(repr(e))
class _UniffiHandleMap:
    """
    A map where inserting, getting and removing data is synchronized with a lock.
    """

    def __init__(self):
        # type Handle = int
        self._map = {}  # type: Dict[Handle, Any]
        self._lock = threading.Lock()
        self._counter = itertools.count()

    def insert(self, obj):
        with self._lock:
            handle = next(self._counter)
            self._map[handle] = obj
            return handle

    def get(self, handle):
        try:
            with self._lock:
                return self._map[handle]
        except KeyError:
            raise InternalError("_UniffiHandleMap.get: Invalid handle")

    def remove(self, handle):
        try:
            with self._lock:
                return self._map.pop(handle)
        except KeyError:
            raise InternalError("_UniffiHandleMap.remove: Invalid handle")

    def __len__(self):
        return len(self._map)
# Types conforming to `_UniffiConverterPrimitive` pass themselves directly over the FFI.
class _UniffiConverterPrimitive:
    @classmethod
    def lift(cls, value):
        return value

    @classmethod
    def lower(cls, value):
        return value

class _UniffiConverterPrimitiveInt(_UniffiConverterPrimitive):
    @classmethod
    def check_lower(cls, value):
        try:
            value = value.__index__()
        except Exception:
            raise TypeError("'{}' object cannot be interpreted as an integer".format(type(value).__name__))
        if not isinstance(value, int):
            raise TypeError("__index__ returned non-int (type {})".format(type(value).__name__))
        if not cls.VALUE_MIN <= value < cls.VALUE_MAX:
            raise ValueError("{} requires {} <= value < {}".format(cls.CLASS_NAME, cls.VALUE_MIN, cls.VALUE_MAX))

class _UniffiConverterPrimitiveFloat(_UniffiConverterPrimitive):
    @classmethod
    def check_lower(cls, value):
        try:
            value = value.__float__()
        except Exception:
            raise TypeError("must be real number, not {}".format(type(value).__name__))
        if not isinstance(value, float):
            raise TypeError("__float__ returned non-float (type {})".format(type(value).__name__))

# Helper class for wrapper types that will always go through a _UniffiRustBuffer.
# Classes should inherit from this and implement the `read` and `write` static methods.
class _UniffiConverterRustBuffer:
    @classmethod
    def lift(cls, rbuf):
        with rbuf.consume_with_stream() as stream:
            return cls.read(stream)

    @classmethod
    def lower(cls, value):
        with _UniffiRustBuffer.alloc_with_builder() as builder:
            cls.write(value, builder)
            return builder.finalize()

# Contains loading, initialization code, and the FFI Function declarations.
# Define some ctypes FFI types that we use in the library

"""
Function pointer for a Rust task, which a callback function that takes a opaque pointer
"""
_UNIFFI_RUST_TASK = ctypes.CFUNCTYPE(None, ctypes.c_void_p, ctypes.c_int8)

def _uniffi_future_callback_t(return_type):
    """
    Factory function to create callback function types for async functions
    """
    return ctypes.CFUNCTYPE(None, ctypes.c_uint64, return_type, _UniffiRustCallStatus)

def _uniffi_load_indirect():
    """
    This is how we find and load the dynamic library provided by the component.
    For now we just look it up by name.
    """
    if sys.platform == "darwin":
        libname = "lib{}.dylib"
    elif sys.platform.startswith("win"):
        # As of python3.8, ctypes does not seem to search $PATH when loading DLLs.
        # We could use `os.add_dll_directory` to configure the search path, but
        # it doesn't feel right to mess with application-wide settings. Let's
        # assume that the `.dll` is next to the `.py` file and load by full path.
        libname = os.path.join(
            os.path.dirname(__file__),
            "{}.dll",
        )
    else:
        # Anything else must be an ELF platform - Linux, *BSD, Solaris/illumos
        libname = "lib{}.so"

    libname = libname.format("pubkycore")
    path = os.path.join(os.path.dirname(__file__), libname)
    lib = ctypes.cdll.LoadLibrary(path)
    return lib

def _uniffi_check_contract_api_version(lib):
    # Get the bindings contract version from our ComponentInterface
    bindings_contract_version = 29
    # Get the scaffolding contract version by calling the into the dylib
    scaffolding_contract_version = lib.ffi_pubkycore_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version:
        raise InternalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")

def _uniffi_check_api_checksums(lib):
    if lib.uniffi_pubkycore_checksum_func_auth() != 36598:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_pubkycore_checksum_func_create_recovery_file() != 13366:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_pubkycore_checksum_func_decrypt_recovery_file() != 56578:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_pubkycore_checksum_func_delete_file() != 37648:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_pubkycore_checksum_func_generate_mnemonic_phrase() != 38398:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_pubkycore_checksum_func_generate_mnemonic_phrase_and_keypair() != 13119:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_pubkycore_checksum_func_generate_secret_key() != 63319:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_pubkycore_checksum_func_get() != 12463:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_pubkycore_checksum_func_get_homeserver() != 35947:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_pubkycore_checksum_func_get_public_key_from_secret_key() != 65274:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_pubkycore_checksum_func_get_signup_token() != 7931:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_pubkycore_checksum_func_list() != 14351:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_pubkycore_checksum_func_mnemonic_phrase_to_keypair() != 59088:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_pubkycore_checksum_func_parse_auth_url() != 47180:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_pubkycore_checksum_func_publish() != 60897:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_pubkycore_checksum_func_publish_https() != 43863:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_pubkycore_checksum_func_put() != 29897:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_pubkycore_checksum_func_remove_event_listener() != 3828:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_pubkycore_checksum_func_republish_homeserver() != 20001:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_pubkycore_checksum_func_resolve() != 873:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_pubkycore_checksum_func_resolve_https() != 34852:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_pubkycore_checksum_func_revalidate_session() != 12593:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_pubkycore_checksum_func_set_event_listener() != 18894:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_pubkycore_checksum_func_sign_in() != 31244:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_pubkycore_checksum_func_sign_out() != 9048:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_pubkycore_checksum_func_sign_up() != 49409:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_pubkycore_checksum_func_switch_network() != 48346:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_pubkycore_checksum_func_validate_mnemonic_phrase() != 9633:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    if lib.uniffi_pubkycore_checksum_method_eventlistener_on_event_occurred() != 24359:
        raise InternalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")

# A ctypes library to expose the extern-C FFI definitions.
# This is an implementation detail which will be called internally by the public API.

_UniffiLib = _uniffi_load_indirect()
_UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK = ctypes.CFUNCTYPE(None,ctypes.c_uint64,ctypes.c_int8,
)
_UNIFFI_FOREIGN_FUTURE_FREE = ctypes.CFUNCTYPE(None,ctypes.c_uint64,
)
_UNIFFI_CALLBACK_INTERFACE_FREE = ctypes.CFUNCTYPE(None,ctypes.c_uint64,
)
class _UniffiForeignFuture(ctypes.Structure):
    _fields_ = [
        ("handle", ctypes.c_uint64),
        ("free", _UNIFFI_FOREIGN_FUTURE_FREE),
    ]
class _UniffiForeignFutureStructU8(ctypes.Structure):
    _fields_ = [
        ("return_value", ctypes.c_uint8),
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_U8 = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructU8,
)
class _UniffiForeignFutureStructI8(ctypes.Structure):
    _fields_ = [
        ("return_value", ctypes.c_int8),
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_I8 = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructI8,
)
class _UniffiForeignFutureStructU16(ctypes.Structure):
    _fields_ = [
        ("return_value", ctypes.c_uint16),
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_U16 = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructU16,
)
class _UniffiForeignFutureStructI16(ctypes.Structure):
    _fields_ = [
        ("return_value", ctypes.c_int16),
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_I16 = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructI16,
)
class _UniffiForeignFutureStructU32(ctypes.Structure):
    _fields_ = [
        ("return_value", ctypes.c_uint32),
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_U32 = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructU32,
)
class _UniffiForeignFutureStructI32(ctypes.Structure):
    _fields_ = [
        ("return_value", ctypes.c_int32),
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_I32 = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructI32,
)
class _UniffiForeignFutureStructU64(ctypes.Structure):
    _fields_ = [
        ("return_value", ctypes.c_uint64),
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_U64 = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructU64,
)
class _UniffiForeignFutureStructI64(ctypes.Structure):
    _fields_ = [
        ("return_value", ctypes.c_int64),
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_I64 = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructI64,
)
class _UniffiForeignFutureStructF32(ctypes.Structure):
    _fields_ = [
        ("return_value", ctypes.c_float),
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_F32 = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructF32,
)
class _UniffiForeignFutureStructF64(ctypes.Structure):
    _fields_ = [
        ("return_value", ctypes.c_double),
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_F64 = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructF64,
)
class _UniffiForeignFutureStructPointer(ctypes.Structure):
    _fields_ = [
        ("return_value", ctypes.c_void_p),
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_POINTER = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructPointer,
)
class _UniffiForeignFutureStructRustBuffer(ctypes.Structure):
    _fields_ = [
        ("return_value", _UniffiRustBuffer),
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructRustBuffer,
)
class _UniffiForeignFutureStructVoid(ctypes.Structure):
    _fields_ = [
        ("call_status", _UniffiRustCallStatus),
    ]
_UNIFFI_FOREIGN_FUTURE_COMPLETE_VOID = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiForeignFutureStructVoid,
)
_UNIFFI_CALLBACK_INTERFACE_EVENT_LISTENER_METHOD0 = ctypes.CFUNCTYPE(None,ctypes.c_uint64,_UniffiRustBuffer,ctypes.c_void_p,
    ctypes.POINTER(_UniffiRustCallStatus),
)
class _UniffiVTableCallbackInterfaceEventListener(ctypes.Structure):
    _fields_ = [
        ("on_event_occurred", _UNIFFI_CALLBACK_INTERFACE_EVENT_LISTENER_METHOD0),
        ("uniffi_free", _UNIFFI_CALLBACK_INTERFACE_FREE),
    ]
_UniffiLib.uniffi_pubkycore_fn_clone_eventnotifier.argtypes = (
    ctypes.c_void_p,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_pubkycore_fn_clone_eventnotifier.restype = ctypes.c_void_p
_UniffiLib.uniffi_pubkycore_fn_free_eventnotifier.argtypes = (
    ctypes.c_void_p,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_pubkycore_fn_free_eventnotifier.restype = None
_UniffiLib.uniffi_pubkycore_fn_init_callback_vtable_eventlistener.argtypes = (
    ctypes.POINTER(_UniffiVTableCallbackInterfaceEventListener),
)
_UniffiLib.uniffi_pubkycore_fn_init_callback_vtable_eventlistener.restype = None
_UniffiLib.uniffi_pubkycore_fn_func_auth.argtypes = (
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_pubkycore_fn_func_auth.restype = _UniffiRustBuffer
_UniffiLib.uniffi_pubkycore_fn_func_create_recovery_file.argtypes = (
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_pubkycore_fn_func_create_recovery_file.restype = _UniffiRustBuffer
_UniffiLib.uniffi_pubkycore_fn_func_decrypt_recovery_file.argtypes = (
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_pubkycore_fn_func_decrypt_recovery_file.restype = _UniffiRustBuffer
_UniffiLib.uniffi_pubkycore_fn_func_delete_file.argtypes = (
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_pubkycore_fn_func_delete_file.restype = _UniffiRustBuffer
_UniffiLib.uniffi_pubkycore_fn_func_generate_mnemonic_phrase.argtypes = (
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_pubkycore_fn_func_generate_mnemonic_phrase.restype = _UniffiRustBuffer
_UniffiLib.uniffi_pubkycore_fn_func_generate_mnemonic_phrase_and_keypair.argtypes = (
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_pubkycore_fn_func_generate_mnemonic_phrase_and_keypair.restype = _UniffiRustBuffer
_UniffiLib.uniffi_pubkycore_fn_func_generate_secret_key.argtypes = (
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_pubkycore_fn_func_generate_secret_key.restype = _UniffiRustBuffer
_UniffiLib.uniffi_pubkycore_fn_func_get.argtypes = (
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_pubkycore_fn_func_get.restype = _UniffiRustBuffer
_UniffiLib.uniffi_pubkycore_fn_func_get_homeserver.argtypes = (
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_pubkycore_fn_func_get_homeserver.restype = _UniffiRustBuffer
_UniffiLib.uniffi_pubkycore_fn_func_get_public_key_from_secret_key.argtypes = (
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_pubkycore_fn_func_get_public_key_from_secret_key.restype = _UniffiRustBuffer
_UniffiLib.uniffi_pubkycore_fn_func_get_signup_token.argtypes = (
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_pubkycore_fn_func_get_signup_token.restype = _UniffiRustBuffer
_UniffiLib.uniffi_pubkycore_fn_func_list.argtypes = (
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_pubkycore_fn_func_list.restype = _UniffiRustBuffer
_UniffiLib.uniffi_pubkycore_fn_func_mnemonic_phrase_to_keypair.argtypes = (
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_pubkycore_fn_func_mnemonic_phrase_to_keypair.restype = _UniffiRustBuffer
_UniffiLib.uniffi_pubkycore_fn_func_parse_auth_url.argtypes = (
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_pubkycore_fn_func_parse_auth_url.restype = _UniffiRustBuffer
_UniffiLib.uniffi_pubkycore_fn_func_publish.argtypes = (
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_pubkycore_fn_func_publish.restype = _UniffiRustBuffer
_UniffiLib.uniffi_pubkycore_fn_func_publish_https.argtypes = (
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_pubkycore_fn_func_publish_https.restype = _UniffiRustBuffer
_UniffiLib.uniffi_pubkycore_fn_func_put.argtypes = (
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_pubkycore_fn_func_put.restype = _UniffiRustBuffer
_UniffiLib.uniffi_pubkycore_fn_func_remove_event_listener.argtypes = (
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_pubkycore_fn_func_remove_event_listener.restype = None
_UniffiLib.uniffi_pubkycore_fn_func_republish_homeserver.argtypes = (
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_pubkycore_fn_func_republish_homeserver.restype = _UniffiRustBuffer
_UniffiLib.uniffi_pubkycore_fn_func_resolve.argtypes = (
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_pubkycore_fn_func_resolve.restype = _UniffiRustBuffer
_UniffiLib.uniffi_pubkycore_fn_func_resolve_https.argtypes = (
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_pubkycore_fn_func_resolve_https.restype = _UniffiRustBuffer
_UniffiLib.uniffi_pubkycore_fn_func_revalidate_session.argtypes = (
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_pubkycore_fn_func_revalidate_session.restype = _UniffiRustBuffer
_UniffiLib.uniffi_pubkycore_fn_func_set_event_listener.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_pubkycore_fn_func_set_event_listener.restype = None
_UniffiLib.uniffi_pubkycore_fn_func_sign_in.argtypes = (
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_pubkycore_fn_func_sign_in.restype = _UniffiRustBuffer
_UniffiLib.uniffi_pubkycore_fn_func_sign_out.argtypes = (
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_pubkycore_fn_func_sign_out.restype = _UniffiRustBuffer
_UniffiLib.uniffi_pubkycore_fn_func_sign_up.argtypes = (
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_pubkycore_fn_func_sign_up.restype = _UniffiRustBuffer
_UniffiLib.uniffi_pubkycore_fn_func_switch_network.argtypes = (
    ctypes.c_int8,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_pubkycore_fn_func_switch_network.restype = _UniffiRustBuffer
_UniffiLib.uniffi_pubkycore_fn_func_validate_mnemonic_phrase.argtypes = (
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.uniffi_pubkycore_fn_func_validate_mnemonic_phrase.restype = _UniffiRustBuffer
_UniffiLib.ffi_pubkycore_rustbuffer_alloc.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_pubkycore_rustbuffer_alloc.restype = _UniffiRustBuffer
_UniffiLib.ffi_pubkycore_rustbuffer_from_bytes.argtypes = (
    _UniffiForeignBytes,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_pubkycore_rustbuffer_from_bytes.restype = _UniffiRustBuffer
_UniffiLib.ffi_pubkycore_rustbuffer_free.argtypes = (
    _UniffiRustBuffer,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_pubkycore_rustbuffer_free.restype = None
_UniffiLib.ffi_pubkycore_rustbuffer_reserve.argtypes = (
    _UniffiRustBuffer,
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_pubkycore_rustbuffer_reserve.restype = _UniffiRustBuffer
_UniffiLib.ffi_pubkycore_rust_future_poll_u8.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_pubkycore_rust_future_poll_u8.restype = None
_UniffiLib.ffi_pubkycore_rust_future_cancel_u8.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_pubkycore_rust_future_cancel_u8.restype = None
_UniffiLib.ffi_pubkycore_rust_future_free_u8.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_pubkycore_rust_future_free_u8.restype = None
_UniffiLib.ffi_pubkycore_rust_future_complete_u8.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_pubkycore_rust_future_complete_u8.restype = ctypes.c_uint8
_UniffiLib.ffi_pubkycore_rust_future_poll_i8.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_pubkycore_rust_future_poll_i8.restype = None
_UniffiLib.ffi_pubkycore_rust_future_cancel_i8.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_pubkycore_rust_future_cancel_i8.restype = None
_UniffiLib.ffi_pubkycore_rust_future_free_i8.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_pubkycore_rust_future_free_i8.restype = None
_UniffiLib.ffi_pubkycore_rust_future_complete_i8.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_pubkycore_rust_future_complete_i8.restype = ctypes.c_int8
_UniffiLib.ffi_pubkycore_rust_future_poll_u16.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_pubkycore_rust_future_poll_u16.restype = None
_UniffiLib.ffi_pubkycore_rust_future_cancel_u16.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_pubkycore_rust_future_cancel_u16.restype = None
_UniffiLib.ffi_pubkycore_rust_future_free_u16.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_pubkycore_rust_future_free_u16.restype = None
_UniffiLib.ffi_pubkycore_rust_future_complete_u16.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_pubkycore_rust_future_complete_u16.restype = ctypes.c_uint16
_UniffiLib.ffi_pubkycore_rust_future_poll_i16.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_pubkycore_rust_future_poll_i16.restype = None
_UniffiLib.ffi_pubkycore_rust_future_cancel_i16.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_pubkycore_rust_future_cancel_i16.restype = None
_UniffiLib.ffi_pubkycore_rust_future_free_i16.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_pubkycore_rust_future_free_i16.restype = None
_UniffiLib.ffi_pubkycore_rust_future_complete_i16.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_pubkycore_rust_future_complete_i16.restype = ctypes.c_int16
_UniffiLib.ffi_pubkycore_rust_future_poll_u32.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_pubkycore_rust_future_poll_u32.restype = None
_UniffiLib.ffi_pubkycore_rust_future_cancel_u32.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_pubkycore_rust_future_cancel_u32.restype = None
_UniffiLib.ffi_pubkycore_rust_future_free_u32.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_pubkycore_rust_future_free_u32.restype = None
_UniffiLib.ffi_pubkycore_rust_future_complete_u32.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_pubkycore_rust_future_complete_u32.restype = ctypes.c_uint32
_UniffiLib.ffi_pubkycore_rust_future_poll_i32.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_pubkycore_rust_future_poll_i32.restype = None
_UniffiLib.ffi_pubkycore_rust_future_cancel_i32.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_pubkycore_rust_future_cancel_i32.restype = None
_UniffiLib.ffi_pubkycore_rust_future_free_i32.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_pubkycore_rust_future_free_i32.restype = None
_UniffiLib.ffi_pubkycore_rust_future_complete_i32.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_pubkycore_rust_future_complete_i32.restype = ctypes.c_int32
_UniffiLib.ffi_pubkycore_rust_future_poll_u64.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_pubkycore_rust_future_poll_u64.restype = None
_UniffiLib.ffi_pubkycore_rust_future_cancel_u64.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_pubkycore_rust_future_cancel_u64.restype = None
_UniffiLib.ffi_pubkycore_rust_future_free_u64.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_pubkycore_rust_future_free_u64.restype = None
_UniffiLib.ffi_pubkycore_rust_future_complete_u64.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_pubkycore_rust_future_complete_u64.restype = ctypes.c_uint64
_UniffiLib.ffi_pubkycore_rust_future_poll_i64.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_pubkycore_rust_future_poll_i64.restype = None
_UniffiLib.ffi_pubkycore_rust_future_cancel_i64.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_pubkycore_rust_future_cancel_i64.restype = None
_UniffiLib.ffi_pubkycore_rust_future_free_i64.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_pubkycore_rust_future_free_i64.restype = None
_UniffiLib.ffi_pubkycore_rust_future_complete_i64.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_pubkycore_rust_future_complete_i64.restype = ctypes.c_int64
_UniffiLib.ffi_pubkycore_rust_future_poll_f32.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_pubkycore_rust_future_poll_f32.restype = None
_UniffiLib.ffi_pubkycore_rust_future_cancel_f32.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_pubkycore_rust_future_cancel_f32.restype = None
_UniffiLib.ffi_pubkycore_rust_future_free_f32.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_pubkycore_rust_future_free_f32.restype = None
_UniffiLib.ffi_pubkycore_rust_future_complete_f32.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_pubkycore_rust_future_complete_f32.restype = ctypes.c_float
_UniffiLib.ffi_pubkycore_rust_future_poll_f64.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_pubkycore_rust_future_poll_f64.restype = None
_UniffiLib.ffi_pubkycore_rust_future_cancel_f64.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_pubkycore_rust_future_cancel_f64.restype = None
_UniffiLib.ffi_pubkycore_rust_future_free_f64.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_pubkycore_rust_future_free_f64.restype = None
_UniffiLib.ffi_pubkycore_rust_future_complete_f64.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_pubkycore_rust_future_complete_f64.restype = ctypes.c_double
_UniffiLib.ffi_pubkycore_rust_future_poll_pointer.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_pubkycore_rust_future_poll_pointer.restype = None
_UniffiLib.ffi_pubkycore_rust_future_cancel_pointer.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_pubkycore_rust_future_cancel_pointer.restype = None
_UniffiLib.ffi_pubkycore_rust_future_free_pointer.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_pubkycore_rust_future_free_pointer.restype = None
_UniffiLib.ffi_pubkycore_rust_future_complete_pointer.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_pubkycore_rust_future_complete_pointer.restype = ctypes.c_void_p
_UniffiLib.ffi_pubkycore_rust_future_poll_rust_buffer.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_pubkycore_rust_future_poll_rust_buffer.restype = None
_UniffiLib.ffi_pubkycore_rust_future_cancel_rust_buffer.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_pubkycore_rust_future_cancel_rust_buffer.restype = None
_UniffiLib.ffi_pubkycore_rust_future_free_rust_buffer.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_pubkycore_rust_future_free_rust_buffer.restype = None
_UniffiLib.ffi_pubkycore_rust_future_complete_rust_buffer.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_pubkycore_rust_future_complete_rust_buffer.restype = _UniffiRustBuffer
_UniffiLib.ffi_pubkycore_rust_future_poll_void.argtypes = (
    ctypes.c_uint64,
    _UNIFFI_RUST_FUTURE_CONTINUATION_CALLBACK,
    ctypes.c_uint64,
)
_UniffiLib.ffi_pubkycore_rust_future_poll_void.restype = None
_UniffiLib.ffi_pubkycore_rust_future_cancel_void.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_pubkycore_rust_future_cancel_void.restype = None
_UniffiLib.ffi_pubkycore_rust_future_free_void.argtypes = (
    ctypes.c_uint64,
)
_UniffiLib.ffi_pubkycore_rust_future_free_void.restype = None
_UniffiLib.ffi_pubkycore_rust_future_complete_void.argtypes = (
    ctypes.c_uint64,
    ctypes.POINTER(_UniffiRustCallStatus),
)
_UniffiLib.ffi_pubkycore_rust_future_complete_void.restype = None
_UniffiLib.uniffi_pubkycore_checksum_func_auth.argtypes = (
)
_UniffiLib.uniffi_pubkycore_checksum_func_auth.restype = ctypes.c_uint16
_UniffiLib.uniffi_pubkycore_checksum_func_create_recovery_file.argtypes = (
)
_UniffiLib.uniffi_pubkycore_checksum_func_create_recovery_file.restype = ctypes.c_uint16
_UniffiLib.uniffi_pubkycore_checksum_func_decrypt_recovery_file.argtypes = (
)
_UniffiLib.uniffi_pubkycore_checksum_func_decrypt_recovery_file.restype = ctypes.c_uint16
_UniffiLib.uniffi_pubkycore_checksum_func_delete_file.argtypes = (
)
_UniffiLib.uniffi_pubkycore_checksum_func_delete_file.restype = ctypes.c_uint16
_UniffiLib.uniffi_pubkycore_checksum_func_generate_mnemonic_phrase.argtypes = (
)
_UniffiLib.uniffi_pubkycore_checksum_func_generate_mnemonic_phrase.restype = ctypes.c_uint16
_UniffiLib.uniffi_pubkycore_checksum_func_generate_mnemonic_phrase_and_keypair.argtypes = (
)
_UniffiLib.uniffi_pubkycore_checksum_func_generate_mnemonic_phrase_and_keypair.restype = ctypes.c_uint16
_UniffiLib.uniffi_pubkycore_checksum_func_generate_secret_key.argtypes = (
)
_UniffiLib.uniffi_pubkycore_checksum_func_generate_secret_key.restype = ctypes.c_uint16
_UniffiLib.uniffi_pubkycore_checksum_func_get.argtypes = (
)
_UniffiLib.uniffi_pubkycore_checksum_func_get.restype = ctypes.c_uint16
_UniffiLib.uniffi_pubkycore_checksum_func_get_homeserver.argtypes = (
)
_UniffiLib.uniffi_pubkycore_checksum_func_get_homeserver.restype = ctypes.c_uint16
_UniffiLib.uniffi_pubkycore_checksum_func_get_public_key_from_secret_key.argtypes = (
)
_UniffiLib.uniffi_pubkycore_checksum_func_get_public_key_from_secret_key.restype = ctypes.c_uint16
_UniffiLib.uniffi_pubkycore_checksum_func_get_signup_token.argtypes = (
)
_UniffiLib.uniffi_pubkycore_checksum_func_get_signup_token.restype = ctypes.c_uint16
_UniffiLib.uniffi_pubkycore_checksum_func_list.argtypes = (
)
_UniffiLib.uniffi_pubkycore_checksum_func_list.restype = ctypes.c_uint16
_UniffiLib.uniffi_pubkycore_checksum_func_mnemonic_phrase_to_keypair.argtypes = (
)
_UniffiLib.uniffi_pubkycore_checksum_func_mnemonic_phrase_to_keypair.restype = ctypes.c_uint16
_UniffiLib.uniffi_pubkycore_checksum_func_parse_auth_url.argtypes = (
)
_UniffiLib.uniffi_pubkycore_checksum_func_parse_auth_url.restype = ctypes.c_uint16
_UniffiLib.uniffi_pubkycore_checksum_func_publish.argtypes = (
)
_UniffiLib.uniffi_pubkycore_checksum_func_publish.restype = ctypes.c_uint16
_UniffiLib.uniffi_pubkycore_checksum_func_publish_https.argtypes = (
)
_UniffiLib.uniffi_pubkycore_checksum_func_publish_https.restype = ctypes.c_uint16
_UniffiLib.uniffi_pubkycore_checksum_func_put.argtypes = (
)
_UniffiLib.uniffi_pubkycore_checksum_func_put.restype = ctypes.c_uint16
_UniffiLib.uniffi_pubkycore_checksum_func_remove_event_listener.argtypes = (
)
_UniffiLib.uniffi_pubkycore_checksum_func_remove_event_listener.restype = ctypes.c_uint16
_UniffiLib.uniffi_pubkycore_checksum_func_republish_homeserver.argtypes = (
)
_UniffiLib.uniffi_pubkycore_checksum_func_republish_homeserver.restype = ctypes.c_uint16
_UniffiLib.uniffi_pubkycore_checksum_func_resolve.argtypes = (
)
_UniffiLib.uniffi_pubkycore_checksum_func_resolve.restype = ctypes.c_uint16
_UniffiLib.uniffi_pubkycore_checksum_func_resolve_https.argtypes = (
)
_UniffiLib.uniffi_pubkycore_checksum_func_resolve_https.restype = ctypes.c_uint16
_UniffiLib.uniffi_pubkycore_checksum_func_revalidate_session.argtypes = (
)
_UniffiLib.uniffi_pubkycore_checksum_func_revalidate_session.restype = ctypes.c_uint16
_UniffiLib.uniffi_pubkycore_checksum_func_set_event_listener.argtypes = (
)
_UniffiLib.uniffi_pubkycore_checksum_func_set_event_listener.restype = ctypes.c_uint16
_UniffiLib.uniffi_pubkycore_checksum_func_sign_in.argtypes = (
)
_UniffiLib.uniffi_pubkycore_checksum_func_sign_in.restype = ctypes.c_uint16
_UniffiLib.uniffi_pubkycore_checksum_func_sign_out.argtypes = (
)
_UniffiLib.uniffi_pubkycore_checksum_func_sign_out.restype = ctypes.c_uint16
_UniffiLib.uniffi_pubkycore_checksum_func_sign_up.argtypes = (
)
_UniffiLib.uniffi_pubkycore_checksum_func_sign_up.restype = ctypes.c_uint16
_UniffiLib.uniffi_pubkycore_checksum_func_switch_network.argtypes = (
)
_UniffiLib.uniffi_pubkycore_checksum_func_switch_network.restype = ctypes.c_uint16
_UniffiLib.uniffi_pubkycore_checksum_func_validate_mnemonic_phrase.argtypes = (
)
_UniffiLib.uniffi_pubkycore_checksum_func_validate_mnemonic_phrase.restype = ctypes.c_uint16
_UniffiLib.uniffi_pubkycore_checksum_method_eventlistener_on_event_occurred.argtypes = (
)
_UniffiLib.uniffi_pubkycore_checksum_method_eventlistener_on_event_occurred.restype = ctypes.c_uint16
_UniffiLib.ffi_pubkycore_uniffi_contract_version.argtypes = (
)
_UniffiLib.ffi_pubkycore_uniffi_contract_version.restype = ctypes.c_uint32

_uniffi_check_contract_api_version(_UniffiLib)
# _uniffi_check_api_checksums(_UniffiLib)

# Public interface members begin here.
# Magic number for the Rust proxy to call using the same mechanism as every other method,
# to free the callback once it's dropped by Rust.
_UNIFFI_IDX_CALLBACK_FREE = 0
# Return codes for callback calls
_UNIFFI_CALLBACK_SUCCESS = 0
_UNIFFI_CALLBACK_ERROR = 1
_UNIFFI_CALLBACK_UNEXPECTED_ERROR = 2

class _UniffiCallbackInterfaceFfiConverter:
    _handle_map = _UniffiHandleMap()

    @classmethod
    def lift(cls, handle):
        return cls._handle_map.get(handle)

    @classmethod
    def read(cls, buf):
        handle = buf.read_u64()
        cls.lift(handle)

    @classmethod
    def check_lower(cls, cb):
        pass

    @classmethod
    def lower(cls, cb):
        handle = cls._handle_map.insert(cb)
        return handle

    @classmethod
    def write(cls, cb, buf):
        buf.write_u64(cls.lower(cb))

class _UniffiConverterBool:
    @classmethod
    def check_lower(cls, value):
        return not not value

    @classmethod
    def lower(cls, value):
        return 1 if value else 0

    @staticmethod
    def lift(value):
        return value != 0

    @classmethod
    def read(cls, buf):
        return cls.lift(buf.read_u8())

    @classmethod
    def write(cls, value, buf):
        buf.write_u8(value)

class _UniffiConverterString:
    @staticmethod
    def check_lower(value):
        if not isinstance(value, str):
            raise TypeError("argument must be str, not {}".format(type(value).__name__))
        return value

    @staticmethod
    def read(buf):
        size = buf.read_i32()
        if size < 0:
            raise InternalError("Unexpected negative string length")
        utf8_bytes = buf.read(size)
        return utf8_bytes.decode("utf-8")

    @staticmethod
    def write(value, buf):
        utf8_bytes = value.encode("utf-8")
        buf.write_i32(len(utf8_bytes))
        buf.write(utf8_bytes)

    @staticmethod
    def lift(buf):
        with buf.consume_with_stream() as stream:
            return stream.read(stream.remaining()).decode("utf-8")

    @staticmethod
    def lower(value):
        with _UniffiRustBuffer.alloc_with_builder() as builder:
            builder.write(value.encode("utf-8"))
            return builder.finalize()






class EventListener(typing.Protocol):
    def on_event_occurred(self, event_data: "str"):
        raise NotImplementedError


# Put all the bits inside a class to keep the top-level namespace clean
class _UniffiTraitImplEventListener:
    # For each method, generate a callback function to pass to Rust

    @_UNIFFI_CALLBACK_INTERFACE_EVENT_LISTENER_METHOD0
    def on_event_occurred(
            uniffi_handle,
            event_data,
            uniffi_out_return,
            uniffi_call_status_ptr,
        ):
        uniffi_obj = _UniffiConverterTypeEventListener._handle_map.get(uniffi_handle)
        def make_call():
            args = (_UniffiConverterString.lift(event_data), )
            method = uniffi_obj.on_event_occurred
            return method(*args)

        
        write_return_value = lambda v: None
        _uniffi_trait_interface_call(
                uniffi_call_status_ptr.contents,
                make_call,
                write_return_value,
        )

    @_UNIFFI_CALLBACK_INTERFACE_FREE
    def _uniffi_free(uniffi_handle):
        _UniffiConverterTypeEventListener._handle_map.remove(uniffi_handle)

    # Generate the FFI VTable.  This has a field for each callback interface method.
    _uniffi_vtable = _UniffiVTableCallbackInterfaceEventListener(
        on_event_occurred,
        _uniffi_free
    )
    # Send Rust a pointer to the VTable.  Note: this means we need to keep the struct alive forever,
    # or else bad things will happen when Rust tries to access it.
    _UniffiLib.uniffi_pubkycore_fn_init_callback_vtable_eventlistener(ctypes.byref(_uniffi_vtable))

# The _UniffiConverter which transforms the Callbacks in to Handles to pass to Rust.
_UniffiConverterTypeEventListener = _UniffiCallbackInterfaceFfiConverter()



class _UniffiConverterOptionalString(_UniffiConverterRustBuffer):
    @classmethod
    def check_lower(cls, value):
        if value is not None:
            _UniffiConverterString.check_lower(value)

    @classmethod
    def write(cls, value, buf):
        if value is None:
            buf.write_u8(0)
            return

        buf.write_u8(1)
        _UniffiConverterString.write(value, buf)

    @classmethod
    def read(cls, buf):
        flag = buf.read_u8()
        if flag == 0:
            return None
        elif flag == 1:
            return _UniffiConverterString.read(buf)
        else:
            raise InternalError("Unexpected flag byte for optional type")



class _UniffiConverterSequenceString(_UniffiConverterRustBuffer):
    @classmethod
    def check_lower(cls, value):
        for item in value:
            _UniffiConverterString.check_lower(item)

    @classmethod
    def write(cls, value, buf):
        items = len(value)
        buf.write_i32(items)
        for item in value:
            _UniffiConverterString.write(item, buf)

    @classmethod
    def read(cls, buf):
        count = buf.read_i32()
        if count < 0:
            raise InternalError("Unexpected negative sequence length")

        return [
            _UniffiConverterString.read(buf) for i in range(count)
        ]

# objects.
class EventNotifierProtocol(typing.Protocol):
    pass
# EventNotifier is a Rust-only trait - it's a wrapper around a Rust implementation.
class EventNotifier():
    _pointer: ctypes.c_void_p
    
    def __init__(self, *args, **kwargs):
        raise ValueError("This class has no default constructor")

    def __del__(self):
        # In case of partial initialization of instances.
        pointer = getattr(self, "_pointer", None)
        if pointer is not None:
            _uniffi_rust_call(_UniffiLib.uniffi_pubkycore_fn_free_eventnotifier, pointer)

    def _uniffi_clone_pointer(self):
        return _uniffi_rust_call(_UniffiLib.uniffi_pubkycore_fn_clone_eventnotifier, self._pointer)

    # Used by alternative constructors or any methods which return this type.
    @classmethod
    def _make_instance_(cls, pointer):
        # Lightly yucky way to bypass the usual __init__ logic
        # and just create a new instance with the required pointer.
        inst = cls.__new__(cls)
        inst._pointer = pointer
        return inst



class _UniffiConverterTypeEventNotifier:

    @staticmethod
    def lift(value: int):
        return EventNotifier._make_instance_(value)

    @staticmethod
    def check_lower(value: EventNotifier):
        if not isinstance(value, EventNotifier):
            raise TypeError("Expected EventNotifier instance, {} found".format(type(value).__name__))

    @staticmethod
    def lower(value: EventNotifierProtocol):
        if not isinstance(value, EventNotifier):
            raise TypeError("Expected EventNotifier instance, {} found".format(type(value).__name__))
        return value._uniffi_clone_pointer()

    @classmethod
    def read(cls, buf: _UniffiRustBuffer):
        ptr = buf.read_u64()
        if ptr == 0:
            raise InternalError("Raw pointer value was null")
        return cls.lift(ptr)

    @classmethod
    def write(cls, value: EventNotifierProtocol, buf: _UniffiRustBuffer):
        buf.write_u64(cls.lower(value))

# Async support

def auth(url: "str",secret_key: "str") -> "typing.List[str]":
    _UniffiConverterString.check_lower(url)
    
    _UniffiConverterString.check_lower(secret_key)
    
    return _UniffiConverterSequenceString.lift(_uniffi_rust_call(_UniffiLib.uniffi_pubkycore_fn_func_auth,
        _UniffiConverterString.lower(url),
        _UniffiConverterString.lower(secret_key)))


def create_recovery_file(secret_key: "str",passphrase: "str") -> "typing.List[str]":
    _UniffiConverterString.check_lower(secret_key)
    
    _UniffiConverterString.check_lower(passphrase)
    
    return _UniffiConverterSequenceString.lift(_uniffi_rust_call(_UniffiLib.uniffi_pubkycore_fn_func_create_recovery_file,
        _UniffiConverterString.lower(secret_key),
        _UniffiConverterString.lower(passphrase)))


def decrypt_recovery_file(recovery_file: "str",passphrase: "str") -> "typing.List[str]":
    _UniffiConverterString.check_lower(recovery_file)
    
    _UniffiConverterString.check_lower(passphrase)
    
    return _UniffiConverterSequenceString.lift(_uniffi_rust_call(_UniffiLib.uniffi_pubkycore_fn_func_decrypt_recovery_file,
        _UniffiConverterString.lower(recovery_file),
        _UniffiConverterString.lower(passphrase)))


def delete_file(url: "str",secret_key: "str") -> "typing.List[str]":
    _UniffiConverterString.check_lower(url)
    
    _UniffiConverterString.check_lower(secret_key)
    
    return _UniffiConverterSequenceString.lift(_uniffi_rust_call(_UniffiLib.uniffi_pubkycore_fn_func_delete_file,
        _UniffiConverterString.lower(url),
        _UniffiConverterString.lower(secret_key)))


def generate_mnemonic_phrase() -> "typing.List[str]":
    return _UniffiConverterSequenceString.lift(_uniffi_rust_call(_UniffiLib.uniffi_pubkycore_fn_func_generate_mnemonic_phrase,))


def generate_mnemonic_phrase_and_keypair() -> "typing.List[str]":
    return _UniffiConverterSequenceString.lift(_uniffi_rust_call(_UniffiLib.uniffi_pubkycore_fn_func_generate_mnemonic_phrase_and_keypair,))


def generate_secret_key() -> "typing.List[str]":
    return _UniffiConverterSequenceString.lift(_uniffi_rust_call(_UniffiLib.uniffi_pubkycore_fn_func_generate_secret_key,))


def get(url: "str") -> "typing.List[str]":
    _UniffiConverterString.check_lower(url)
    
    return _UniffiConverterSequenceString.lift(_uniffi_rust_call(_UniffiLib.uniffi_pubkycore_fn_func_get,
        _UniffiConverterString.lower(url)))


def get_homeserver(pubky: "str") -> "typing.List[str]":
    _UniffiConverterString.check_lower(pubky)
    
    return _UniffiConverterSequenceString.lift(_uniffi_rust_call(_UniffiLib.uniffi_pubkycore_fn_func_get_homeserver,
        _UniffiConverterString.lower(pubky)))


def get_public_key_from_secret_key(secret_key: "str") -> "typing.List[str]":
    _UniffiConverterString.check_lower(secret_key)
    
    return _UniffiConverterSequenceString.lift(_uniffi_rust_call(_UniffiLib.uniffi_pubkycore_fn_func_get_public_key_from_secret_key,
        _UniffiConverterString.lower(secret_key)))


def get_signup_token(homeserver_pubky: "str",admin_password: "str") -> "typing.List[str]":
    _UniffiConverterString.check_lower(homeserver_pubky)
    
    _UniffiConverterString.check_lower(admin_password)
    
    return _UniffiConverterSequenceString.lift(_uniffi_rust_call(_UniffiLib.uniffi_pubkycore_fn_func_get_signup_token,
        _UniffiConverterString.lower(homeserver_pubky),
        _UniffiConverterString.lower(admin_password)))


def list(url: "str") -> "typing.List[str]":
    _UniffiConverterString.check_lower(url)
    
    return _UniffiConverterSequenceString.lift(_uniffi_rust_call(_UniffiLib.uniffi_pubkycore_fn_func_list,
        _UniffiConverterString.lower(url)))


def mnemonic_phrase_to_keypair(mnemonic_phrase: "str") -> "typing.List[str]":
    _UniffiConverterString.check_lower(mnemonic_phrase)
    
    return _UniffiConverterSequenceString.lift(_uniffi_rust_call(_UniffiLib.uniffi_pubkycore_fn_func_mnemonic_phrase_to_keypair,
        _UniffiConverterString.lower(mnemonic_phrase)))


def parse_auth_url(url: "str") -> "typing.List[str]":
    _UniffiConverterString.check_lower(url)
    
    return _UniffiConverterSequenceString.lift(_uniffi_rust_call(_UniffiLib.uniffi_pubkycore_fn_func_parse_auth_url,
        _UniffiConverterString.lower(url)))


def publish(record_name: "str",record_content: "str",secret_key: "str") -> "typing.List[str]":
    _UniffiConverterString.check_lower(record_name)
    
    _UniffiConverterString.check_lower(record_content)
    
    _UniffiConverterString.check_lower(secret_key)
    
    return _UniffiConverterSequenceString.lift(_uniffi_rust_call(_UniffiLib.uniffi_pubkycore_fn_func_publish,
        _UniffiConverterString.lower(record_name),
        _UniffiConverterString.lower(record_content),
        _UniffiConverterString.lower(secret_key)))


def publish_https(record_name: "str",target: "str",secret_key: "str") -> "typing.List[str]":
    _UniffiConverterString.check_lower(record_name)
    
    _UniffiConverterString.check_lower(target)
    
    _UniffiConverterString.check_lower(secret_key)
    
    return _UniffiConverterSequenceString.lift(_uniffi_rust_call(_UniffiLib.uniffi_pubkycore_fn_func_publish_https,
        _UniffiConverterString.lower(record_name),
        _UniffiConverterString.lower(target),
        _UniffiConverterString.lower(secret_key)))


def put(url: "str",content: "str",secret_key: "str") -> "typing.List[str]":
    _UniffiConverterString.check_lower(url)
    
    _UniffiConverterString.check_lower(content)
    
    _UniffiConverterString.check_lower(secret_key)
    
    return _UniffiConverterSequenceString.lift(_uniffi_rust_call(_UniffiLib.uniffi_pubkycore_fn_func_put,
        _UniffiConverterString.lower(url),
        _UniffiConverterString.lower(content),
        _UniffiConverterString.lower(secret_key)))


def remove_event_listener() -> None:
    _uniffi_rust_call(_UniffiLib.uniffi_pubkycore_fn_func_remove_event_listener,)


def republish_homeserver(secret_key: "str",homeserver: "str") -> "typing.List[str]":
    _UniffiConverterString.check_lower(secret_key)
    
    _UniffiConverterString.check_lower(homeserver)
    
    return _UniffiConverterSequenceString.lift(_uniffi_rust_call(_UniffiLib.uniffi_pubkycore_fn_func_republish_homeserver,
        _UniffiConverterString.lower(secret_key),
        _UniffiConverterString.lower(homeserver)))


def resolve(public_key: "str") -> "typing.List[str]":
    """
    * Resolve a signed packet from a public key
    * @param public_key The public key to resolve
    * @returns A vector with two elements: the first element is a boolean indicating success or failure,
    * and the second element is the response data (either an error message or the resolved signed packet)
    *
    """

    _UniffiConverterString.check_lower(public_key)
    
    return _UniffiConverterSequenceString.lift(_uniffi_rust_call(_UniffiLib.uniffi_pubkycore_fn_func_resolve,
        _UniffiConverterString.lower(public_key)))


def resolve_https(public_key: "str") -> "typing.List[str]":
    _UniffiConverterString.check_lower(public_key)
    
    return _UniffiConverterSequenceString.lift(_uniffi_rust_call(_UniffiLib.uniffi_pubkycore_fn_func_resolve_https,
        _UniffiConverterString.lower(public_key)))


def revalidate_session(session_secret: "str") -> "typing.List[str]":
    _UniffiConverterString.check_lower(session_secret)
    
    return _UniffiConverterSequenceString.lift(_uniffi_rust_call(_UniffiLib.uniffi_pubkycore_fn_func_revalidate_session,
        _UniffiConverterString.lower(session_secret)))


def set_event_listener(listener: "EventListener") -> None:
    _UniffiConverterTypeEventListener.check_lower(listener)
    
    _uniffi_rust_call(_UniffiLib.uniffi_pubkycore_fn_func_set_event_listener,
        _UniffiConverterTypeEventListener.lower(listener))


def sign_in(secret_key: "str") -> "typing.List[str]":
    _UniffiConverterString.check_lower(secret_key)
    
    return _UniffiConverterSequenceString.lift(_uniffi_rust_call(_UniffiLib.uniffi_pubkycore_fn_func_sign_in,
        _UniffiConverterString.lower(secret_key)))


def sign_out(session_secret: "str") -> "typing.List[str]":
    _UniffiConverterString.check_lower(session_secret)
    
    return _UniffiConverterSequenceString.lift(_uniffi_rust_call(_UniffiLib.uniffi_pubkycore_fn_func_sign_out,
        _UniffiConverterString.lower(session_secret)))


def sign_up(secret_key: "str",homeserver: "str",signup_token: "typing.Optional[str]") -> "typing.List[str]":
    _UniffiConverterString.check_lower(secret_key)
    
    _UniffiConverterString.check_lower(homeserver)
    
    _UniffiConverterOptionalString.check_lower(signup_token)
    
    return _UniffiConverterSequenceString.lift(_uniffi_rust_call(_UniffiLib.uniffi_pubkycore_fn_func_sign_up,
        _UniffiConverterString.lower(secret_key),
        _UniffiConverterString.lower(homeserver),
        _UniffiConverterOptionalString.lower(signup_token)))


def switch_network(use_testnet: "bool") -> "typing.List[str]":
    _UniffiConverterBool.check_lower(use_testnet)
    
    return _UniffiConverterSequenceString.lift(_uniffi_rust_call(_UniffiLib.uniffi_pubkycore_fn_func_switch_network,
        _UniffiConverterBool.lower(use_testnet)))


def validate_mnemonic_phrase(mnemonic_phrase: "str") -> "typing.List[str]":
    _UniffiConverterString.check_lower(mnemonic_phrase)
    
    return _UniffiConverterSequenceString.lift(_uniffi_rust_call(_UniffiLib.uniffi_pubkycore_fn_func_validate_mnemonic_phrase,
        _UniffiConverterString.lower(mnemonic_phrase)))


__all__ = [
    "InternalError",
    "auth",
    "create_recovery_file",
    "decrypt_recovery_file",
    "delete_file",
    "generate_mnemonic_phrase",
    "generate_mnemonic_phrase_and_keypair",
    "generate_secret_key",
    "get",
    "get_homeserver",
    "get_public_key_from_secret_key",
    "get_signup_token",
    "list",
    "mnemonic_phrase_to_keypair",
    "parse_auth_url",
    "publish",
    "publish_https",
    "put",
    "remove_event_listener",
    "republish_homeserver",
    "resolve",
    "resolve_https",
    "revalidate_session",
    "set_event_listener",
    "sign_in",
    "sign_out",
    "sign_up",
    "switch_network",
    "validate_mnemonic_phrase",
    "EventNotifier",
    "EventListener",
]

